### ISSUE TITLE
TLSVERIFY should be enabled by default in all buildah tasks

### ISSUE THREAD

**Issue by tumido** [thoth-station/helm-charts#13]
`TLSVERIFY` parameter defaults to `false` on all build tasks. This is probably because we don't mount the proper SSL certificates in `PipelineRun`.

https://github.com/thoth-station/helm-charts/blob/30ab8051d7e75d178e4e1b77acfaf1663586729c/charts/meteor-pipelines/templates/issue-release-task.yaml#L11-L15

https://github.com/thoth-station/helm-charts/blob/30ab8051d7e75d178e4e1b77acfaf1663586729c/charts/meteor-pipelines/templates/overlay-build-task.yaml#L50-L54

https://github.com/thoth-station/helm-charts/blob/30ab8051d7e75d178e4e1b77acfaf1663586729c/charts/meteor-pipelines/templates/pr-build-release.yaml#L47-L51

https://github.com/thoth-station/helm-charts/blob/30ab8051d7e75d178e4e1b77acfaf1663586729c/charts/meteor-pipelines/templates/pr-build.yaml#L31-L35

https://github.com/thoth-station/helm-charts/blob/30ab8051d7e75d178e4e1b77acfaf1663586729c/charts/meteor-pipelines/templates/tag-build.yaml#L8-L12

https://github.com/thoth-station/helm-charts/blob/30ab8051d7e75d178e4e1b77acfaf1663586729c/charts/meteor-pipelines/templates/tag-release-task.yaml#L44-L48

_Originally posted by @tumido in https://github.com/thoth-station/helm-charts/pull/9#discussion_r760179820_

To resolve this we need to change:

1. Change build `Task`s as follows:
    1. Obviously set the `TLSVERIFY` default to `true`
    2. Add a new optional workspace `sslcertdir`
    3. Change the build and push steps to include:
       ```diff
       + [[ "$(workspaces.sslcertdir.bound)" == "true" ]] && CERT_DIR_FLAG="--cert-dir $(workspaces.sslcertdir.path)"
       + buildah ${CERT_DIR_FLAG} --storage-driver=$(params.STORAGE_DRIVER) push \
       - buildah --storage-driver=$(params.STORAGE_DRIVER) push \
       ```
2. Change all the `Pipeline` resources which uses the `Task`s from above as follows:
    1. Add a new optional workspace `sslcertdir`
    2. Pass the `sslcertdir` workspace to the build task

3. Change the `PipelineRun` resources triggering the pipeline to populate the workspace with:
    ```yaml
    kind: PipelineRun
    spec:
      workspaces:
      - name: sslcertdir
        configMap:
          name: openshift-service-ca.crt
          defaultMode: 420
          items:
          - key: service-ca.crt
            path: ca.crt
    ```

Each namespace should already be populated with `openshift-service-ca.crt` configmap which has `service-ca.crt` key that contains the required certificate. `buildah` command requires the certificate to be named `ca.crt` to be recognized as valid so, keep that in mind. This ensures the internal CA authority of current OpenShift cluster is respected and imported properly.

Example solution for meteor: https://github.com/tumido/helm-charts/commit/1a61ff023ff1919cef6e8ac365a64c19b497aa77
Upstream solution:
- https://github.com/tektoncd/catalog/blob/main/task/buildah/0.3/samples/openshift-internal-registry.yaml (we don't need to reference config map from another namespace since it gets imported automatically)
- https://github.com/tektoncd/catalog/blob/main/task/buildah/0.3/buildah.yaml

**Comment by codificat** [comment]
Might be related: https://bugzilla.redhat.com/show_bug.cgi?id=1879680#c5

According to that comment, tekton should take care of mounting the relevant certs since pipelines 1.4; however, just tested that this still fails on a cluster with openshift pipelines 1.6.1... and, well, the bugzilla is still open.

**Comment by Gregory-Pereira** [comment]
Awesome, thanks Pep I will keep my eyes on this report!

**Comment by Gregory-Pereira** [comment]
Since #32 was merged, can we close this issue, or should we wait for more evidence that it works successfully for use cases that work with private registries?

**Comment by codificat** [comment]
> Since #32 was merged, can we close this issue, or should we wait for more evidence that it works successfully for use cases that work with private registries?

I was hoping to find the reason why it works out of the box on OpenShift Pipelines (through automatic transparent injection of the service-ca cert) vs the workaround applied in #32, but this can be done later.

For the purpose of the issue itself, this is resolved now, so let's
/close
