### ISSUE TITLE
[SPIKE]Investigate the changes needed to adapt to KubeFlow Notebook controller

### ISSUE THREAD

**Issue by codificat** [thoth-station/helm-charts#47]
Open Data Hub is moving from JupyterHub to KFNBC.  How does that impact the Meteor/CNBi/Thoth pipelines?

Does that affect the use of ImageStreams?

Can the controller/pipelines be made independent of ImageStreams? (so that things work on plain Kubernetes)

**Comment by codificat** [comment]
Another potential implication to verify: RBAC needed to access cross-namespace (dev, operator, jupyter)

**Comment by harshad16** [comment]
Kubeflow Notebook Controller uses ODH-Dashboard as the UI.
![Screenshot from 2022-11-03 15-17-06](https://user-images.githubusercontent.com/14028058/199814080-b8a23177-1a8f-48cb-9380-74aa1025041d.png)

The UI is pretty much the same as jupyterhub.

The imagestream is used as the primary option, they are displayed for users to pick, to construct the notebook.
The same labels as required for jupyterhub are required for kubeflow-notebook-controller.
` opendatahub.io/notebook-image: 'true'`

The imagestream need to be in the same namespace as the ODH-Dashboard, for them to appear on the list.

**Comment by harshad16** [comment]
closing this all the details are provided in previous comment 
if anything is missing please reopen this.
Thanks.

**Comment by harshad16** [comment]
Questions asked during review:

- Does images require something extra for them to function on kubeflow notebook controller ?
Based on the documentation from kubeflow , it is stated
that images should have these requirements:
https://www.kubeflow.org/docs/components/notebooks/container-images/#image-requirements
