### ISSUE TITLE
Create a pipeline for the PackageList build type

### ISSUE THREAD

**Issue by codificat** [thoth-station/helm-charts#48]
The CNBi `PackageList` build type needs a backing pipeline

## Acceptance criteria
- [x] thoth-station/helm-charts#50
- [x] thoth-station/meteor-operator#107

Additional context:
- https://issues.redhat.com/browse/RHODS-3203
- check requirement 1

**Comment by goern** [comment]
does this depend on the decision how we want to handle (internal) repos for the builds?

**Comment by VannTen** [comment]
A couple of things:

- a list of packages -> how do we define that. At the minimum, I think we would
  need package + version. But would that be version ranges (aka, what's in a
  `Pipfile` for example) or exact versions (like `Pipfile.lock`) ?
- Regarding the internal git repository:
  I'm not sure about this. I don't see what we would gain going from a package
  list to a git repository. In fact, I'd rather have it the other way around and
  the package list being the canonical representation (here I see the possible
  process to transform: get a git repository, list its dependency, build a
  sdist/wheel, package list = dependency + sdist/wheel)

**Comment by goern** [comment]
for an MVP let's mimic requirements.txt, so the bare minimum is `package_name`, and it might be a version specifier. We should be able to get a `thamos advise` on the input. 

adding the internal git repo would enable us to write the list of packages from the first step, add all things required by thoth (`.thoth.yaml`) and run a `thamos advise` ... @codificat

**Comment by VannTen** [comment]
On Tue, Oct 04, 2022 at 05:20:42AM -0700, Christoph Görn wrote:
> for an MVP let's mimic requirements.txt, so the bare minimum is `package_name`, and it might be a version specifier. We should be able to get a `thamos advise` on the input. 

ACK

> adding the internal git repo would enable us to write the list of packages from the first step, add all things required by thoth (`.thoth.yaml`) and run a `thamos advise` ... 

Why do we need a git repo for that ? pip (or potentially something else)
does not require it, does it ? Or maybe thamos does ?

**Comment by VannTen** [comment]
On Tue, Oct 04, 2022 at 05:20:42AM -0700, Christoph Görn wrote:
> for an MVP let's mimic requirements.txt

Actually, regarding that. The requirements.txt format is poorly
specified (see the first note in pip documentation[1]). We can go with
that for now, but let's keep that item in mind.

PEP 440[2] and/or 508[3] for thinking about the format we'll decide to
accept (not that we'll use necessarily everything).

[1]: https://pip.pypa.io/en/stable/reference/requirements-file-format/
[2]: https://peps.python.org/pep-0440
[3]: https://peps.python.org/pep-0508

**Comment by codificat** [comment]
This has now been completed end to end (dashboard, controller and pipeline) via the issues referenced above.

To summarize an answer to prior comments: the approach for now is to *not* rely on a git repo and accept package/version specifications from the controller as a list. Internally, the pipeline does create a requirements file for final installation, but this is not exposed externally.

/close
