### ISSUE TITLE
Implement the pipeline to implement the PackageList build type

### ISSUE THREAD

**Issue by harshad16** [thoth-station/helm-charts#50]
Design a standalone pipeline that implements the logic required to create an image from a list of packages.

See [the example PackageList CNBi](https://github.com/thoth-station/opendatahub-cnbi/blob/fa7254656b60b69e7751924cb988b1ddda99ad9e/README.md#example-1) for the expected arguments to the pipeline.

## Acceptance criteria

- [ ] a tekton pipeline definition that builds a container image spawnable by jupyterlab that includes all the packages as specified by a CNBi resource.
- [ ] adjustments to the CNBi resource design (if appropriate)

**Comment by VannTen** [comment]
https://hackmd.io/@thoth-station/ryWW3dsRc#Build-based-on-a-list-of-Python-packages-PackageList
This being the example in question
