### ISSUE TITLE
Release meteor-pipelines-0.2.0 in index.yaml

### ISSUE THREAD

**Issue by tumido** [thoth-station/helm-charts#7]
@goern what do I need to run/do to add [releases/meteor-pipelines-0.2.0](https://github.com/thoth-station/helm-charts/releases/tag/meteor-pipelines-0.2.0) to https://github.com/thoth-station/helm-charts/blob/gh-pages/index.yaml ? Is triggering the Release GitHub Actions workflow enough? I saw you've update the `index.yaml` manually last time... Is this expected to happen automatically?

**Comment by goern** [comment]
Heya, I manually rereleased 0.2.0 please check if it looks good.

**Comment by codificat** [comment]
Automated releases are working now.
/close
